spring.application.name=vitalux_e3h8

# Configuracao do Banco de Dados com suporte a variáveis de ambiente
spring.datasource.url=jdbc:postgresql://dpg-d975alupuehc73ffv3mg-a.oregon-postgres.render.com/vitalux_e3h8
spring.datasource.username=vitalux_e3h8_user
spring.datasource.password=FaGtnREEAqXoXs1MQc7JwhiQ2beN0UU8
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.use-fqn=true

GROQ_MODEL=${GROQ_MODEL}
GROQ_API_KEY=${GROQ_API_KEY}
