spring.application.name=vitalux

spring.datasource.url=jdbc:postgresql://dpg-d6t92c5m5p6s73b82ll0-a.oregon-postgres.render.com/vitalux
spring.datasource.username=vitalux_user
spring.datasource.password=iCwU7szoe2sLXeZmOS0pLaAPjZo0hoYF
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
