spring.application.name=vitalux_pzld

# Configuracao do Banco de Dados com suporte a variáveis de ambiente
spring.datasource.url=jdbc:postgresql://dpg-d7j39im7r5hc73cgsl30-a.oregon-postgres.render.com/vitalux_pzld
spring.datasource.username=vitalux_pzld_user
spring.datasource.password=INn9BnljutMSOTpaXskamVDKud2AMREX
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# Configuracao do Swagger/OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.use-fqn=true

